//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_ShoebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sdirecttestdbEntities : DbContext
    {
        public sdirecttestdbEntities()
            : base("name=sdirecttestdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAddress_Sk> tblAddress_Sk { get; set; }
        public virtual DbSet<tblAdminTasks_Sk> tblAdminTasks_Sk { get; set; }
        public virtual DbSet<tblBank_Sk> tblBank_Sk { get; set; }
        public virtual DbSet<tblBankNameUser_Sk> tblBankNameUser_Sk { get; set; }
        public virtual DbSet<tblBorrowMoney_Sk> tblBorrowMoney_Sk { get; set; }
        public virtual DbSet<tblBusinessType_Sk> tblBusinessType_Sk { get; set; }
        public virtual DbSet<tblBuyers_Sk> tblBuyers_Sk { get; set; }
        public virtual DbSet<tblCity_Sk> tblCity_Sk { get; set; }
        public virtual DbSet<tblCountry_Sk> tblCountry_Sk { get; set; }
        public virtual DbSet<tblInventory_Sk> tblInventory_Sk { get; set; }
        public virtual DbSet<tblItems_Sk> tblItems_Sk { get; set; }
        public virtual DbSet<tblNotifications_Sk> tblNotifications_Sk { get; set; }
        public virtual DbSet<tblOrders_Sk> tblOrders_Sk { get; set; }
        public virtual DbSet<tblOrderStatus_Sk> tblOrderStatus_Sk { get; set; }
        public virtual DbSet<tblPaymentMethod_Sk> tblPaymentMethod_Sk { get; set; }
        public virtual DbSet<tblProducts_Sk> tblProducts_Sk { get; set; }
        public virtual DbSet<tblProductsCategory_Sk> tblProductsCategory_Sk { get; set; }
        public virtual DbSet<tblRole_Sk> tblRole_Sk { get; set; }
        public virtual DbSet<tblSellers_Sk> tblSellers_Sk { get; set; }
        public virtual DbSet<tblSellerStatus_Sk> tblSellerStatus_Sk { get; set; }
        public virtual DbSet<tblShippingMethod_Sk> tblShippingMethod_Sk { get; set; }
        public virtual DbSet<tblState_Sk> tblState_Sk { get; set; }
        public virtual DbSet<tbltemHistory_Sk> tbltemHistory_Sk { get; set; }
        public virtual DbSet<tblUser_Sk> tblUser_Sk { get; set; }
        public virtual DbSet<tblDebitCards_Sk> tblDebitCards_Sk { get; set; }
    }
}
