//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_ShoebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBank_Sk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBank_Sk()
        {
            this.tblBankNameUser_Sk = new HashSet<tblBankNameUser_Sk>();
            this.tblPaymentMethod_Sk = new HashSet<tblPaymentMethod_Sk>();
            this.tblSellers_Sk = new HashSet<tblSellers_Sk>();
        }
    
        public int BankId { get; set; }
        public string BankName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime IsCreatedOn { get; set; }
        public string IsCreatedBy { get; set; }
        public System.DateTime IsUpdatedOn { get; set; }
        public string IsUpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string IsDeletedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBankNameUser_Sk> tblBankNameUser_Sk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPaymentMethod_Sk> tblPaymentMethod_Sk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSellers_Sk> tblSellers_Sk { get; set; }
    }
}
