//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_ShoebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItems_Sk
    {
        public int ItemId { get; set; }
        public int OrderId { get; set; }
        public int InventoryId { get; set; }
        public int ItemCount { get; set; }
        public int NetPrice { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime IsCreatedOn { get; set; }
        public string IsCreatedBy { get; set; }
        public System.DateTime IsUpdatedOn { get; set; }
        public string IsUpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string IsDeletedBy { get; set; }
    
        public virtual tblInventory_Sk tblInventory_Sk { get; set; }
        public virtual tblOrders_Sk tblOrders_Sk { get; set; }
    }
}
