//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_ShoebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotifications_Sk
    {
        public int NotificationId { get; set; }
        public int SellerId { get; set; }
        public int OrderId { get; set; }
        public int BuyerId { get; set; }
        public string Notification { get; set; }
        public bool IsRead { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime IsCreatedOn { get; set; }
        public string IsCreatedBy { get; set; }
        public System.DateTime IsUpdatedOn { get; set; }
        public string IsUpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string IsDeletedBy { get; set; }
    
        public virtual tblBuyers_Sk tblBuyers_Sk { get; set; }
        public virtual tblOrders_Sk tblOrders_Sk { get; set; }
        public virtual tblSellers_Sk tblSellers_Sk { get; set; }
    }
}
