//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_ShoebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSellerStatus_Sk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSellerStatus_Sk()
        {
            this.tblSellers_Sk = new HashSet<tblSellers_Sk>();
        }
    
        public int SellerStatusId { get; set; }
        public int UserId { get; set; }
        public string StatusName { get; set; }
        public System.DateTime StatusChangedOn { get; set; }
        public string StatusChangedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime IsCreatedOn { get; set; }
        public string IsCreatedBy { get; set; }
        public System.DateTime IsUpdatedOn { get; set; }
        public string IsUpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string IsDeletedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSellers_Sk> tblSellers_Sk { get; set; }
        public virtual tblUser_Sk tblUser_Sk { get; set; }
    }
}
