//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBuyers_Sk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBuyers_Sk()
        {
            this.tblOrders_Sk = new HashSet<tblOrders_Sk>();
            this.tblOrders_Sk1 = new HashSet<tblOrders_Sk>();
        }
    
        public int BuyerId { get; set; }
        public int UserId { get; set; }
        public int ShippingAddress { get; set; }
        public int BillingAddress { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime IsCreatedOn { get; set; }
        public string IsCreatedBy { get; set; }
        public System.DateTime IsUpdatedOn { get; set; }
        public string IsUpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string IsDeletedBy { get; set; }
    
        public virtual tblAddress_Sk tblAddress_Sk { get; set; }
        public virtual tblAddress_Sk tblAddress_Sk1 { get; set; }
        public virtual tblUser_Sk tblUser_Sk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrders_Sk> tblOrders_Sk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrders_Sk> tblOrders_Sk1 { get; set; }
    }
}
