//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOtp_Sk
    {
        public int OtpId { get; set; }
        public string Email { get; set; }
        public int OTP { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> IsUpdatedOn { get; set; }
        public string IsUpdatedBy { get; set; }
        public Nullable<System.DateTime> IsCreatedOn { get; set; }
        public string IsCreatedBy { get; set; }
    }
}
